### PR TITLE
Added Debouncing feature

### PR DESCRIPTION
**Pull request by hardikhere**
issue #21 
Added an optional feature of Debouncing 
to use it set useDebounce = {true}
you can also set debounceWait = {number in ms} default is 300ms and debounceOptions like maxWait and leading
It will reduce the number of API hits so that no api hit go unused

### CODE REVIEW

**Comment by cottonstartiet** [comment]
I dont think adding a dependency on lodadh for such a feature is a good idea. 
Could this be modified so that if anyone wants to add debounce, he could do it by usign his own implementation (using lodash or some other).

**Comment by hardikhere** [comment]
> I dont think adding a dependency on lodadh for such a feature is a good idea.
> Could this be modified so that if anyone wants to add debounce, he could do it by usign his own implementation (using lodash or some other).

Anyone can also use api that Google provides, then why u need this package? To save time right?
The whole lodash is not installed just lodash.debounce is installed which is very light

**Comment by cottonstartiet** [comment]
Agree that whole lodash is not installed. Can I override the behavior? What if there is a bug or I don't like the lodash implementation.

**Comment by hardikhere** [comment]
> Agree that whole lodash is not installed. Can I override the behavior? What if there is a bug or I don't like the lodash implementation.

Ohk then go ahead and make better implementation then lodash debounce let's see😁

**Comment by cottonstartiet** [comment]
@hardikhere useless comment so I'll leave it to the author to decide.
I can only provide clarification on the comment and the concern wrt the design.

**Comment by burhanuday** [comment]
@cottonstartiet can you elaborate on why debounce from lodash would be a bad idea as compared to our own implementation

**Comment by cottonstartiet** [comment]
@burhanuday Sure. Some points that I could think of:

1. Is it a core feature of the library or an addon feature which is good to have? I dont see how "debounce" as a feature is related to Transliterate. It a feature of the input control or data handling.
2. Lodash is known to have security issues in the past but some versions are fine. Tying the implementation to a particular version basically makes this library unusable if there is an issue. This is very common in corporate environments which have security and compliance requirements.
3. In terms of design it would be better if the component api actually exposed some kind of an interceptor, using which we could implement debounce, instead of doing the implementation within the library itself. It could take a function which does debounce if passed. You can add an example on how to implement debounce using lodash if you have the API.
4. Most other UI toolkits do not implement this feature because of the point 3.


For example, react-select, is another very popular library that makes the select/drop-down simpler and more feature rich. It does not have a debounce feature, which seems a good fit because it can also get data from api calls. Even though it doesnt support it out of the box, it can be added via existing api's as shown in this SO answer.
https://stackoverflow.com/questions/55073545/react-select-debounced-async-call-not-displaying-suggestions

**Comment by burhanuday** [comment]
@cottonstartiet i understand your point.
In this case i think @cottonstartiet is right. we should leave it upto the user to provide a debouncing function
a prop like `debounceFunction`. if not undefined will be used as the debouncing function
It keeps this lib lean and makes it mroe flexible

the lodash code should be kept as an example in the docs rather than a built in feature of the lib

**Comment by hardikhere** [comment]
Cool, My concern was, since we are hitting api from our side then It should be our responsibility to handle it well. Thanks great work sir keep doing :)

**Pull request closed without merging**
